### ISSUE TITLE
Acquire DigitalOcean server

### ISSUE THREAD

**Issue by prtksxna** [WordPressGoa/xacuti#1]

**Comment by prtksxna** [comment]
@fabianmossberg said he should be able to do it, but can't assign to him, since he hasn't accepted the organization invitation yet.

**Comment by prtksxna** [comment]
Let @abyshakes know the credentials once you're done so that he can #2.

**Comment by abyshakes** [comment]
I've got the credentials, I'm logging in to setup the server.

**Comment by prtksxna** [comment]
Awesome

**Comment by siddharthashok** [comment]
@abyshakes you are setting up on wordpressgoa.org?
